# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c1c935195e0dae8e240b1dc6144528e94cb6e6dabebf3b00bb83614bd6277c5b33b215173aad792ff2681c9ae207c76d4dad7624ce17d4ba35c20a28ae4457f

test:
  secret_key_base: 45a9f17a901576b927942d3765326648a73e8dcc2e587a24f6641d6e3452d8a3666f2964f072ab75d90d343efb0d0ee2d6001be2b32cd3c548782381b00ead51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
